numero1=input("ingrese un numero:")
numero2=input("ingrese otro numero:")
print("la suma de los numeros es:", int(numero1)+int(numero2))
print("la resta de los numeros es:", int(numero1)-int(numero2))
print("la multiplicacion de los numeros es:", int(numero1)*int(numero2))
print("la division de los numeros es:", int(numero1)/int(numero2))
print("el resto de la division de los numeros es:", int(numero1)%int(numero2))
print("la division entera de los numeros es:", int(numero1)//int(numero2))
print("el valor absoluto del primer numero es:", abs(int(numero1)))
print("el valor absoluto del segundo numero es:", abs(int(numero2)))